version: '3.7'
networks:
  backend:
    name: app
    driver: bridge
volumes:
  postgres-data:
services:
  app:
    image: rodentraid:0.0.1-SNAPSHOT
    container_name: web-app
    environment:
      TZ: "Asia/Singapore"
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend
  db:
    image: postgres:12
    container_name: postgres-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kwsm
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2
